# +------------------------------------------------------+ #
# |       Default Config File ( MST-Sign-Changer )       | #
# +------------------------------------------------------+ #
############################################################
currentLanguage: 'en'
