name: MSTSignChanger
version: 1.5
main: LoveMST.SChanger.sChanger
author: LoveMST
description: Change a certain type of sign
commands:
  SCH:
    description: list all the command that u can use with the sign changer